### ISSUE TITLE
Add yarn support?

### ISSUE THREAD

**Issue by runofthemill** [ninesalt/install-changed#2]
Hello!

This looks like a great package, though I see it's intended to run `npm install` and not `yarn`. Would you be open to a PR that added support for `yarn`?

**Comment by ninesalt** [comment]
Sounds good! I haven't used yarn a lot but I believe you only need to add a command similar to [this](https://github.com/ninesalt/install-changed/blob/master/lib/main.js#L49) and then add a way for users to configure which command they want to run.

**Comment by SassNinja** [comment]
> but I believe you only need to add a command similar to this 

yup, it's just `yarn install`

nice package & idea btw 👍 
has inspired me to write[ my own one](https://github.com/SassNinja/reinstall-node-modules) because I needed more flexibility
