### ISSUE TITLE
Add option to run a different install command

### ISSUE THREAD

**Issue by the21st** [ninesalt/install-changed#7]
Hi, thanks again for creating install-changed! It's helped me a lot in everyday productivity.

The only issue I'm having with my new flow is that sometimes the `npm install` command that this runs changes `package-lock.json` and I end up with unexpected changed file in my repo.

For this purpose, there's [`npm ci`](https://docs.npmjs.com/cli/ci.html) which installs from the lockfile, is potentially faster, and doesn't change package-lock.json. Could you add an option to enable running `npm ci` instead of `npm install` if the `package.json` file is changed?

**Comment by ryanburnette** [comment]
@ninesalt Love the lib, thanks for writing it.

@the21st I might need the same update. I'll PR if I fork and write it myself. For now `npm install` works for me.

**Comment by thdk** [comment]
@ryanburnette @the21st 
Can you have a look at my PR for this and let me know if that would solve your issue?

**Comment by the21st** [comment]
@thdk that looks great, thank you!
